#![crate_type = "lib"]
#![crate_type = "rlib"]
#![crate_type = "dylib"]
#![crate_name = "cfd_rust"]

#[macro_use]
extern crate slice_as_array;

pub mod address;
pub mod common;
pub mod confidential_address;
pub mod descriptor;
pub mod hdwallet;
pub mod key;
pub mod script;
pub mod transaction;

pub use common::request_json;
pub use common::Amount;
pub use common::ByteData;
pub use common::CfdError;
pub use common::Network;

pub use address::Address;
pub use address::AddressType;
pub use address::HashType;
pub use address::WitnessVersion;
pub use confidential_address::ConfidentialAddress;
pub use descriptor::Descriptor;
pub use descriptor::DescriptorKeyType;
pub use descriptor::DescriptorScriptData;
pub use descriptor::DescriptorScriptType;
pub use descriptor::KeyData;
pub use hdwallet::ExtKey;
pub use hdwallet::ExtPrivkey;
pub use hdwallet::ExtPubkey;
pub use hdwallet::HDWallet;
pub use hdwallet::MnemonicLanguage;
pub use hdwallet::XPRIV_MAINNET_VERSION;
pub use hdwallet::XPRIV_TESTNET_VERSION;
pub use hdwallet::XPUB_MAINNET_VERSION;
pub use hdwallet::XPUB_TESTNET_VERSION;
pub use key::Privkey;
pub use key::Pubkey;
pub use key::SigHashType;
pub use key::SignParameter;
pub use key::PRIVKEY_SIZE;
pub use key::PUBKEY_COMPRESSED_SIZE;
pub use key::PUBKEY_UNCOMPRESSED_SIZE;
pub use script::Script;
pub use transaction::OutPoint;
pub use transaction::Transaction;
pub use transaction::TxIn;
pub use transaction::TxInData;
pub use transaction::TxOut;
pub use transaction::TxOutData;
pub use transaction::Txid;
pub use transaction::UtxoData;
pub use transaction::SEQUENCE_LOCK_TIME_DISABLE;
pub use transaction::SEQUENCE_LOCK_TIME_ENABLE_MAX;
